return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.2.4",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 100,
  height = 100,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 12,
  nextobjectid = 65,
  properties = {},
  tilesets = {
    {
      name = "tiled_playa",
      firstgid = 1,
      filename = "tiled_playa.tsx",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 4,
      image = "tiled_playa.png",
      imagewidth = 128,
      imageheight = 96,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 12,
      tiles = {
        {
          id = 2,
          animation = {
            {
              tileid = 2,
              duration = 300
            },
            {
              tileid = 3,
              duration = 300
            }
          }
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 3,
      name = "Suelo",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2ctu6zAMhOGk6Ps/c7spkAZOogvJGUn/YuDdORQ/k7bT++12+/rN/YDrX76DE12juk+VHhkWeOCxw9V5T53kkTkbeOy5p07yiLbAw2cu8MBj9WuFRWbt6v4xF3t7rOiwo0fmbODhsaeqe+TQR9c99ThzeGj3lKo3Dv1kT+GBBx6neERbXD3Pq3rl0E9XD4WPQz9X8Wjxme2pQz9naldZZM2RQ1938+iZo2cDh76utqeyzdR9xeO/i7qvI3sKD5/rrhareexuofZ4lci5ePf/OPqqPd71b2YueoydXFru109nytj/M30aqdnJ41M90S6ZZx+t0cVj1G7meVFRY29t6t5G2vQ8t6vq2nkuWkw+pbomh1kl8e9TPffcbNS9y/R4dhk9d8T7y4m7s+W+Hv038PAIHl7BwytVHlh4eGDh4YGBhwcOcSY8r71y9T3TG/UZCCHktLCjfcL3lUdm3jNxybHg+8sj0d/F6vOsnozfKdRnWjl4eCXag70VZ4KHT/DwzKwLFrkuvT54aHyuoq6REEIIiQzPO31a3g3VNZ6Qnnd0da27p/dbSV3vbhn9ZsUj14Lf2LT9j/rtU32mVeP8N5qW35Fao+6zymHU41UfI/+26mqV6TDiUVGP437NuO9mz1dVj5NHpcOqHlUmqvO614eHV30KjxX2MR544PHZQ+2Ch9ec4IEHHjoP9flWu3/w8Kq7Ylet6PFYe9VcVMyGyiHyfqtwqZqNHTwyXSocdvW4shndS9UWu3tczUxLKvsfcf+s5rFK8PBJxnMPjzkLtcPpHs/PLbXDyR6ODid6ODv8XX8AGSpv1w=="
    },
    {
      type = "tilelayer",
      id = 4,
      name = "Suelo2",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T+1lC6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAbnEAAAQ=="
    },
    {
      type = "objectgroup",
      id = 2,
      name = "Borrador",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 5,
          name = "punto_inicio",
          type = "",
          shape = "point",
          x = 263,
          y = 132,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "arbol",
          type = "",
          shape = "point",
          x = 989,
          y = 533,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "roca",
          type = "",
          shape = "point",
          x = 388,
          y = 627,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "estrella",
          type = "",
          shape = "point",
          x = 660,
          y = 234,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "punto_enemigo",
          type = "",
          shape = "point",
          x = 520,
          y = 452,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "punto_enemigo",
          type = "",
          shape = "point",
          x = 624,
          y = 811,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "arbol",
          type = "",
          shape = "point",
          x = 173,
          y = 533,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "arbol",
          type = "",
          shape = "point",
          x = 989,
          y = 533,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "arbol",
          type = "",
          shape = "point",
          x = 1037,
          y = 713,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "arbol",
          type = "",
          shape = "point",
          x = 1044,
          y = 252,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "arbol",
          type = "",
          shape = "point",
          x = 1200,
          y = 460,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "arbol",
          type = "",
          shape = "point",
          x = 1412,
          y = 228,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "punto_enemigo",
          type = "",
          shape = "point",
          x = 2752,
          y = 412,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "punto_enemigo",
          type = "",
          shape = "point",
          x = 2572,
          y = 1296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "punto_enemigo",
          type = "",
          shape = "point",
          x = 2676,
          y = 2924,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "punto_enemigo",
          type = "",
          shape = "point",
          x = 864,
          y = 2800,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "arbol",
          type = "",
          shape = "point",
          x = 1468,
          y = 1728,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "arbol",
          type = "",
          shape = "point",
          x = 1624,
          y = 1856,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "arbol",
          type = "",
          shape = "point",
          x = 1408,
          y = 1864,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "arbol",
          type = "",
          shape = "point",
          x = 1852,
          y = 1180,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "roca",
          type = "",
          shape = "point",
          x = 1680,
          y = 164,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "roca",
          type = "",
          shape = "point",
          x = 1384,
          y = 640,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "roca",
          type = "",
          shape = "point",
          x = 2628,
          y = 552,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "roca",
          type = "",
          shape = "point",
          x = 2848,
          y = 144,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "roca",
          type = "",
          shape = "point",
          x = 2979,
          y = 578,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "roca",
          type = "",
          shape = "point",
          x = 2908,
          y = 1309,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "roca",
          type = "",
          shape = "point",
          x = 3004,
          y = 2452,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "roca",
          type = "",
          shape = "point",
          x = 2972,
          y = 3036,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "estrella",
          type = "",
          shape = "point",
          x = 2656,
          y = 232,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "estrella",
          type = "",
          shape = "point",
          x = 2076,
          y = 652,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "estrella",
          type = "",
          shape = "point",
          x = 1238,
          y = 1450,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "estrella",
          type = "",
          shape = "point",
          x = 456,
          y = 1716,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "estrella",
          type = "",
          shape = "point",
          x = 1492,
          y = 2172,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "estrella",
          type = "",
          shape = "point",
          x = 1712,
          y = 2476,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "estrella",
          type = "",
          shape = "point",
          x = 1208,
          y = 2632,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "estrella",
          type = "",
          shape = "point",
          x = 672,
          y = 2532,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "estrella",
          type = "",
          shape = "point",
          x = 552,
          y = 2640,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "estrella",
          type = "",
          shape = "point",
          x = 1372,
          y = 2960,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "estrella",
          type = "",
          shape = "point",
          x = 184,
          y = 2116,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "estrella",
          type = "",
          shape = "point",
          x = 2352,
          y = 2008,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "estrella",
          type = "",
          shape = "point",
          x = 1928,
          y = 2908,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "estrella",
          type = "",
          shape = "point",
          x = 2496,
          y = 2708,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "roca",
          type = "",
          shape = "point",
          x = 280,
          y = 1291,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "roca",
          type = "",
          shape = "point",
          x = 808,
          y = 1540,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "roca",
          type = "",
          shape = "point",
          x = 2280,
          y = 3056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "roca",
          type = "",
          shape = "point",
          x = 3024,
          y = 2768,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "roca",
          type = "",
          shape = "point",
          x = 2772,
          y = 2496,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "roca",
          type = "",
          shape = "point",
          x = 2920,
          y = 1920,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "roca",
          type = "",
          shape = "point",
          x = 2844,
          y = 1040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "roca",
          type = "",
          shape = "point",
          x = 2136,
          y = 148,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "roca",
          type = "",
          shape = "point",
          x = 2100,
          y = 1376,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "roca",
          type = "",
          shape = "point",
          x = 1768,
          y = 712,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "roca",
          type = "",
          shape = "point",
          x = 1972,
          y = 980,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "arrecife",
          type = "",
          shape = "polygon",
          x = 1218,
          y = 862,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 132, y = -27 },
            { x = 202, y = 116 },
            { x = 274, y = 304 },
            { x = 191, y = 448 },
            { x = -40, y = 378 },
            { x = -182, y = 295 },
            { x = -160, y = 73 }
          },
          properties = {
            ["destruible"] = true
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 11,
      name = "Inicios",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 8,
      name = "Objetos",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 10,
      name = "Destruible",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 5,
      name = "Balas",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 6,
      name = "Enemigos",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 7,
      name = "Personajes",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 9,
      name = "Arboles",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    }
  }
}
