return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.2.4",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 100,
  height = 100,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 12,
  nextobjectid = 78,
  properties = {},
  tilesets = {
    {
      name = "tiled_playa",
      firstgid = 1,
      filename = "tiled_playa.tsx",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 4,
      image = "tiled_playa.png",
      imagewidth = 128,
      imageheight = 96,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 12,
      tiles = {
        {
          id = 2,
          properties = {
            ["efecto"] = true
          },
          animation = {
            {
              tileid = 2,
              duration = 300
            },
            {
              tileid = 3,
              duration = 300
            }
          }
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 3,
      name = "Suelo",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["efecto"] = "agua"
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2cty4zAMRFE7+f9/TjapclyyzQeAbpJ30aXdDIgjQJJzv91uX7+5H3D9y3dwomtU96nSI8MCDzx2uDrvqZM8MmcDjz331Eke0RZ4+MwFHnisfq2wyKxd3T/mYm+PFR129MicDTw89lR1jxz66LqnHmcOD+2eUvXGoZ/sKTzwwOMUj2iLq+d5Va8c+unqofBx6OcqHi0+sz116OdM7SqLrDly6OtuHj1z9Gzg0NfV9lS2mbqvePx3Ufd1ZE/h4XPd1WI1j90t1B6vEjkX7/4fR1+1x7v+zcxFj7GTS8v9+ulMGft/pk8jNTt5fKon2iXz7KM1uniM2s08Lypq7K1N3dtIm57ndlVdO89Fi8mnVNfkMKsk/n2q556bjbp3mR7PLqPnjnh/OXF3ttzXo/8GHh7Bwyt4eKXKAwsPDyw8PDDw8MAhzoTntVeuvmd6oz4DIYScFna0T/i+8sjMeyYuORZ8f3kk+rtYfZ7Vk/E7hfpMKwcPr0R7sLfiTPDwCR6emXXBItel1wcPjc9V1DUSQgghkeF5p0/Lu6G6xhPS846urnX39H4rqevdLaPfrHjkWvAbm7b/Ub99qs+0apz/RtPyO1Jr1H1WOYx6vOpj5N9WXa0yHUY8Kupx3K8Z993s+arqcfKodFjVo8pEdV73+vDwqk/hscI+xgMPPD57qF3w8JoTPPDAQ+ehPt9q9w8eXnVX7KoVPR5rr5qLitlQOUTebxUuVbOxg0emS4XDrh5XNqN7qdpid4+rmWlJZf8j7p/VPFYJHj7JeO7hMWehdjjd4/m5pXY42cPR4UQPZ4e/6w/PiFof"
    },
    {
      type = "objectgroup",
      id = 2,
      name = "Borrador",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 5,
          name = "punto_inicio",
          type = "",
          shape = "point",
          x = 263,
          y = 132,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "arbol",
          type = "",
          shape = "point",
          x = 989,
          y = 533,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "roca",
          type = "",
          shape = "point",
          x = 388,
          y = 627,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "estrella",
          type = "",
          shape = "point",
          x = 660,
          y = 234,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "punto_enemigo",
          type = "",
          shape = "point",
          x = 520,
          y = 452,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "punto_enemigo",
          type = "",
          shape = "point",
          x = 624,
          y = 811,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "arbol",
          type = "",
          shape = "point",
          x = 173,
          y = 533,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "arbol",
          type = "",
          shape = "point",
          x = 1037,
          y = 713,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "arbol",
          type = "",
          shape = "point",
          x = 1044,
          y = 252,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "arbol",
          type = "",
          shape = "point",
          x = 1292,
          y = 426,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "arbol",
          type = "",
          shape = "point",
          x = 1450,
          y = 240,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "punto_enemigo",
          type = "",
          shape = "point",
          x = 2752,
          y = 412,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "punto_enemigo",
          type = "",
          shape = "point",
          x = 2572,
          y = 1296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "punto_enemigo",
          type = "",
          shape = "point",
          x = 2676,
          y = 2924,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "punto_enemigo",
          type = "",
          shape = "point",
          x = 864,
          y = 2800,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "arbol",
          type = "",
          shape = "point",
          x = 1468,
          y = 1728,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "arbol",
          type = "",
          shape = "point",
          x = 1624,
          y = 1856,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "arbol",
          type = "",
          shape = "point",
          x = 1408,
          y = 1864,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "arbol",
          type = "",
          shape = "point",
          x = 1852,
          y = 1180,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "roca",
          type = "",
          shape = "point",
          x = 1680,
          y = 164,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "roca",
          type = "",
          shape = "point",
          x = 1384,
          y = 640,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "roca",
          type = "",
          shape = "point",
          x = 2628,
          y = 552,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "roca",
          type = "",
          shape = "point",
          x = 2848,
          y = 144,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "roca",
          type = "",
          shape = "point",
          x = 2979,
          y = 578,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "roca",
          type = "",
          shape = "point",
          x = 2908,
          y = 1309,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "roca",
          type = "",
          shape = "point",
          x = 3004,
          y = 2452,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "roca",
          type = "",
          shape = "point",
          x = 2972,
          y = 3036,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "estrella",
          type = "",
          shape = "point",
          x = 2656,
          y = 232,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "estrella",
          type = "",
          shape = "point",
          x = 2076,
          y = 652,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "estrella",
          type = "",
          shape = "point",
          x = 1238,
          y = 1450,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "estrella",
          type = "",
          shape = "point",
          x = 456,
          y = 1716,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "estrella",
          type = "",
          shape = "point",
          x = 1492,
          y = 2172,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "estrella",
          type = "",
          shape = "point",
          x = 1712,
          y = 2476,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "estrella",
          type = "",
          shape = "point",
          x = 1208,
          y = 2632,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "estrella",
          type = "",
          shape = "point",
          x = 672,
          y = 2532,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "estrella",
          type = "",
          shape = "point",
          x = 552,
          y = 2640,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "estrella",
          type = "",
          shape = "point",
          x = 1372,
          y = 2960,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "estrella",
          type = "",
          shape = "point",
          x = 184,
          y = 2116,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "estrella",
          type = "",
          shape = "point",
          x = 2352,
          y = 2008,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "estrella",
          type = "",
          shape = "point",
          x = 1928,
          y = 2908,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "estrella",
          type = "",
          shape = "point",
          x = 2496,
          y = 2708,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "roca",
          type = "",
          shape = "point",
          x = 280,
          y = 1291,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "roca",
          type = "",
          shape = "point",
          x = 808,
          y = 1540,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "roca",
          type = "",
          shape = "point",
          x = 2280,
          y = 3056,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "roca",
          type = "",
          shape = "point",
          x = 3024,
          y = 2768,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "roca",
          type = "",
          shape = "point",
          x = 2772,
          y = 2496,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "roca",
          type = "",
          shape = "point",
          x = 2920,
          y = 1920,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "roca",
          type = "",
          shape = "point",
          x = 2844,
          y = 1040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "roca",
          type = "",
          shape = "point",
          x = 2136,
          y = 148,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "roca",
          type = "",
          shape = "point",
          x = 2100,
          y = 1376,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "roca",
          type = "",
          shape = "point",
          x = 1768,
          y = 712,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "roca",
          type = "",
          shape = "point",
          x = 1972,
          y = 980,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "arrecife",
          type = "",
          shape = "polygon",
          x = 1218,
          y = 862,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 132, y = -27 },
            { x = 202, y = 116 },
            { x = 274, y = 304 },
            { x = 191, y = 448 },
            { x = -40, y = 378 },
            { x = -182, y = 295 },
            { x = -160, y = 73 }
          },
          properties = {
            ["destruible"] = true
          }
        },
        {
          id = 67,
          name = "arrecife",
          type = "",
          shape = "polygon",
          x = 289.333,
          y = 2129.33,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 56, y = -73.3333 },
            { x = 184, y = -180 },
            { x = 365.333, y = -104 },
            { x = 473.333, y = -18.6667 },
            { x = 428, y = 73.3333 },
            { x = 317.333, y = 197.333 },
            { x = 154.667, y = 176 },
            { x = -9.33333, y = 186.667 }
          },
          properties = {
            ["destruible"] = true
          }
        },
        {
          id = 68,
          name = "arrecife",
          type = "",
          shape = "polygon",
          x = 1053.33,
          y = 1933.33,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -157.333, y = -20 },
            { x = -157.333, y = -164 },
            { x = -109.333, y = -302.667 },
            { x = 84, y = -330.667 },
            { x = 237.333, y = -346.667 },
            { x = 294.667, y = -236 },
            { x = 258.667, y = -81.3333 },
            { x = 168, y = 0 }
          },
          properties = {
            ["destruible"] = true
          }
        },
        {
          id = 69,
          name = "arrecife",
          type = "",
          shape = "polygon",
          x = 880,
          y = 2265.33,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 89.3333, y = -82.6667 },
            { x = 246.667, y = -189.333 },
            { x = 388, y = -101.333 },
            { x = 476, y = 65.3333 },
            { x = 380, y = 137.333 },
            { x = 310.667, y = 222.667 },
            { x = 102.667, y = 213.333 },
            { x = -5.33333, y = 104 }
          },
          properties = {
            ["destruible"] = true
          }
        },
        {
          id = 70,
          name = "arrecife",
          type = "",
          shape = "polygon",
          x = 1903.03,
          y = 2318.18,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 63.6364, y = -133.333 },
            { x = 300, y = -112.121 },
            { x = 527.273, y = -106.061 },
            { x = 454.545, y = 60.6061 },
            { x = 403.03, y = 212.121 },
            { x = 293.939, y = 233.333 },
            { x = 81.8182, y = 293.939 },
            { x = -12.1212, y = 139.394 }
          },
          properties = {
            ["destruible"] = true
          }
        },
        {
          id = 71,
          name = "punto_inicio",
          type = "",
          shape = "point",
          x = 3121.21,
          y = 139.394,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "punto_inicio",
          type = "",
          shape = "point",
          x = 3042.42,
          y = 3112.12,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "punto_inicio",
          type = "",
          shape = "point",
          x = 1417.58,
          y = 2729.7,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "punto_inicio",
          type = "",
          shape = "point",
          x = 1581.82,
          y = 1969.7,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "punto_inicio",
          type = "",
          shape = "point",
          x = 1754.55,
          y = 1057.58,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "punto_inicio",
          type = "",
          shape = "point",
          x = 2651.52,
          y = 1472.73,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "punto_inicio",
          type = "",
          shape = "point",
          x = 151.515,
          y = 3160.61,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 11,
      name = "Inicios",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 8,
      name = "Objetos",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 10,
      name = "Destruible",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 5,
      name = "Balas",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 6,
      name = "Enemigos",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 7,
      name = "Personajes",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 9,
      name = "Arboles",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    }
  }
}
